---
apiVersion: v1
kind: Service
metadata:
  name: routeservice
  #命名空间符合正则表达式"kube-test([-a-z0-9]*[a-z0-9])?"
  namespace: kube-test-travel
  labels:
    app: route-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: route-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routeservice
  namespace: kube-test-travel
  labels:
    app: route-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-service
  template:
    metadata:
      labels:
        app: route-service
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: route-service
          image: $IMAGE_NAME
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /var/log/mclient
              name: log-volume
          env:
            - name: MCLUSTER_IP
              value: "172.16.17.37"
            - name: MCLUSTER_PORT
              value: "30761"
      volumes:
        - name: log-volume
          hostPath:
            path: /data/test-dir/log

