#server.port=8081
#spring.application.name=routeservice
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
##spring.cloud.nacos.discovery.server-addr=172.16.17.37:8848
server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 172.16.17.38:8848
  application:
    name: routeservice

knife4j:
  enable: false
  setting:
    enable-version: true
